export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Lucia Mendez",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Doris Grande",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Pedro Perez",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Carolina Lopez",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Juan Blanco",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "Yenny Fernandez",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Jose Martinez",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "Daniela Ortiz",
  },
  {
    id: 9,
    profilePicture: "person/9.jpeg",
    username: "Fernando Nuñez",
  },
  {
    id: 10,
    profilePicture: "person/10.jpeg",
    username: "Carlos Brunillo",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Programar el React es muy fácil",
    photo: "post/1.jpeg",
    date: "Hace 5 minutos",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpeg",
    date: "Hace 15 minutos",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Java es un lenguaje orientado a objetos",
    photo: "post/3.jpeg",
    date: "Hace 1 hora",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpeg",
    date: "Hace 4 horas",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpeg",
    date: "Hace 5 horas",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpeg",
    date: "Hace 1 día",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/7.jpeg",
    date: "Hace 2 días",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpeg",
    date: "Hace 3 días",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.jpeg",
    date: "Hace 5 días",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "Hace 1 semana",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
